# Generated by Django 4.2.1 on 2023-05-20 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customeruser',
            name='firstname',
            field=models.CharField(default=None, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='customeruser',
            name='lastname',
            field=models.CharField(default=None, max_length=255, null=True),
        ),
    ]
