# Generated by Django 4.2.1 on 2023-05-22 04:28

from django.db import migrations, models
import orders.models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_orderaddress_firstname_orderaddress_lastname_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment',
            field=models.CharField(default='cash', max_length=50),
        ),
        migrations.AlterField(
            model_name='order',
            name='orderno',
            field=models.CharField(default=orders.models.generate_orderid, max_length=255, unique=True),
        ),
    ]
