# Generated by Django 4.2.1 on 2023-05-23 22:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('orders', '0003_order_payment_alter_order_orderno'),
    ]

    operations = [
        migrations.CreateModel(
            name='selleraproval',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('approval', models.CharField(choices=[('pending', 'pending'), ('approved', 'Approved'), ('Rejected', 'Rejected')], default='pending', max_length=50)),
                ('note', models.TextField()),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ordernumber', to='orders.order')),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='selleraccount', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
