# Generated by Django 4.2.1 on 2023-05-06 22:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('category', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('quantity', models.IntegerField()),
                ('image', models.ImageField(upload_to='products/productImg/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='category', to='category.category')),
                ('subcategory', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='subcategory', to='category.subcategory')),
            ],
        ),
        migrations.CreateModel(
            name='Productimage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='products/productImg/')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='productimg', to='products.product', verbose_name='Product Name')),
            ],
        ),
        migrations.CreateModel(
            name='Productdetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('about', models.TextField()),
                ('description', models.TextField()),
                ('size', models.CharField(max_length=255)),
                ('variant', models.CharField(max_length=255)),
                ('SKU', models.CharField(default='', max_length=100)),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='productdetail', to='products.product', verbose_name='Product Name')),
            ],
        ),
    ]
