# Generated by Django 4.2.1 on 2023-05-12 23:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_rename_name_product_item'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='item',
            new_name='name',
        ),
    ]
