# Generated by Django 4.2.1 on 2023-05-13 00:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_rename_item_product_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='image',
            new_name='productimage',
        ),
    ]
