# Generated by Django 4.2.1 on 2023-05-13 00:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_rename_image_product_productimage'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='productimage',
            new_name='mainimage',
        ),
    ]
